version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '0.0.0.0:5432:5432'

  graphql-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - '0.0.0.0:5000:5000'
    command: bash -c "npm install && npm run migrate && npx postgraphile -o --append-plugins postgraphile-plugin-connection-filter --host 0.0.0.0 -c 'postgres://postgres:postgres@db/postgres' --watch --enhance-graphiql --dynamic-json"

  client:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - graphql-server
    ports:
      - '0.0.0.0:4000:3000'
    command: bash -c "npm install && npm run build && npm run start"
